# Generated by Django 3.2.7 on 2021-10-29 00:17

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(choices=[('Card 1', 'Card 1'), ('Card 2', 'Card 2'), ('Card 3', 'Card 3'), ('Card 4', 'Card 4'), ('Card 5', 'Card 5'), ('Card 6', 'Card 6')], default='Card 1', max_length=8, verbose_name='What Card the Info Goes In')),
                ('order_no', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth'), ('Fifth', 'Fifth'), ('Sixth', 'Sixth')], default='First', max_length=20, verbose_name='Location on Page')),
                ('dateTimeCompleted', models.DateTimeField(null=True, verbose_name='Date-Time Completed-Updated')),
                ('title', models.CharField(max_length=50, null=True)),
                ('paragraph', models.TextField(blank=True, max_length=3000, null=True)),
                ('bullet', models.TextField(blank=True, max_length=3000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(choices=[('Card 1', 'Card 1'), ('Card 2', 'Card 2'), ('Card 3', 'Card 3'), ('Card 4', 'Card 4'), ('Card 5', 'Card 5'), ('Card 6', 'Card 6')], default='Card 1', max_length=8, verbose_name='What Card the Info Goes In')),
                ('order_no', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth'), ('Fifth', 'Fifth'), ('Sixth', 'Sixth')], default='First', max_length=20, verbose_name='Location on Page')),
                ('dateTimeCompleted', models.DateTimeField(null=True, verbose_name='Date-Time Completed-Updated')),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('body', models.TextField(blank=True, max_length=3000, null=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to=api.models.nameFile)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=api.models.nameFile)),
                ('video', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(choices=[('Card 1', 'Card 1'), ('Card 2', 'Card 2'), ('Card 3', 'Card 3'), ('Card 4', 'Card 4'), ('Card 5', 'Card 5'), ('Card 6', 'Card 6')], default='Card 1', max_length=8, verbose_name='What Card the Info Goes In')),
                ('order_no', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth'), ('Fifth', 'Fifth'), ('Sixth', 'Sixth')], default='First', max_length=20, verbose_name='Location on Page')),
                ('dateTimeCompleted', models.DateTimeField(null=True, verbose_name='Date-Time Completed-Updated')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('message', models.CharField(blank=True, max_length=350, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image_Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(choices=[('Card 1', 'Card 1'), ('Card 2', 'Card 2'), ('Card 3', 'Card 3'), ('Card 4', 'Card 4'), ('Card 5', 'Card 5'), ('Card 6', 'Card 6')], default='Card 1', max_length=8, verbose_name='What Card the Info Goes In')),
                ('order_no', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth'), ('Fifth', 'Fifth'), ('Sixth', 'Sixth')], default='First', max_length=20, verbose_name='Location on Page')),
                ('dateTimeCompleted', models.DateTimeField(null=True, verbose_name='Date-Time Completed-Updated')),
                ('title', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(choices=[('About', 'About'), ('Archive', 'Archive'), ('Contact', 'Contact'), ('Home', 'Home'), ('Meet the Members', 'Meet the Members'), ('News Letter', 'News Letter')], default='Home', max_length=20, verbose_name='Location in Website')),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.nameFile)),
                ('video_URL', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Meet_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(choices=[('Card 1', 'Card 1'), ('Card 2', 'Card 2'), ('Card 3', 'Card 3'), ('Card 4', 'Card 4'), ('Card 5', 'Card 5'), ('Card 6', 'Card 6')], default='Card 1', max_length=8, verbose_name='What Card the Info Goes In')),
                ('order_no', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth'), ('Fifth', 'Fifth'), ('Sixth', 'Sixth')], default='First', max_length=20, verbose_name='Location on Page')),
                ('dateTimeCompleted', models.DateTimeField(null=True, verbose_name='Date-Time Completed-Updated')),
                ('name', models.CharField(max_length=60, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.nameFile)),
                ('about', models.TextField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='News_Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(choices=[('Card 1', 'Card 1'), ('Card 2', 'Card 2'), ('Card 3', 'Card 3'), ('Card 4', 'Card 4'), ('Card 5', 'Card 5'), ('Card 6', 'Card 6')], default='Card 1', max_length=8, verbose_name='What Card the Info Goes In')),
                ('order_no', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth'), ('Fifth', 'Fifth'), ('Sixth', 'Sixth')], default='First', max_length=20, verbose_name='Location on Page')),
                ('dateTimeCompleted', models.DateTimeField(null=True, verbose_name='Date-Time Completed-Updated')),
                ('title', models.CharField(max_length=30, null=True, verbose_name='Title of the Article')),
                ('author', models.CharField(blank=True, max_length=50, null=True, verbose_name='News Letter Author (Optional)')),
                ('body', models.TextField(max_length=3000, null=True, verbose_name='News Letter body/ paragraph *Enter one paragraph at a time for page break')),
                ('bullet', models.TextField(blank=True, max_length=260, null=True, verbose_name='News Letter Bullet Points (Optional) --- This will be after all of the paragraphs *Enter one at a time')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Party_Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(choices=[('Card 1', 'Card 1'), ('Card 2', 'Card 2'), ('Card 3', 'Card 3'), ('Card 4', 'Card 4'), ('Card 5', 'Card 5'), ('Card 6', 'Card 6')], default='Card 1', max_length=8, verbose_name='What Card the Info Goes In')),
                ('order_no', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth'), ('Fifth', 'Fifth'), ('Sixth', 'Sixth')], default='First', max_length=20, verbose_name='Location on Page')),
                ('dateTimeCompleted', models.DateTimeField(null=True, verbose_name='Date-Time Completed-Updated')),
                ('name', models.CharField(max_length=60, null=True, verbose_name='Name of Member')),
                ('email', models.CharField(max_length=100, null=True, verbose_name="Member's Email")),
                ('position', models.CharField(blank=True, max_length=60, null=True, verbose_name='Position Title (Optional)')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name="Member's Phone Number (Optional)")),
                ('city', models.CharField(blank=True, max_length=24, null=True, verbose_name="Member's Current City (Optional)")),
                ('state', models.CharField(blank=True, max_length=24, null=True, verbose_name="Member's Current State (Optional)")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Policy_Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(choices=[('Card 1', 'Card 1'), ('Card 2', 'Card 2'), ('Card 3', 'Card 3'), ('Card 4', 'Card 4'), ('Card 5', 'Card 5'), ('Card 6', 'Card 6')], default='Card 1', max_length=8, verbose_name='What Card the Info Goes In')),
                ('order_no', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth'), ('Fifth', 'Fifth'), ('Sixth', 'Sixth')], default='First', max_length=20, verbose_name='Location on Page')),
                ('dateTimeCompleted', models.DateTimeField(null=True, verbose_name='Date-Time Completed-Updated')),
                ('position_name', models.CharField(max_length=60, null=True, verbose_name='Position Title')),
                ('description', models.TextField(blank=True, max_length=260, null=True, verbose_name='Position Description (Optional)')),
                ('bullet', models.TextField(blank=True, max_length=260, null=True, verbose_name='Position Bullet Points (Optional) --- This will be after all of the paragraphs *Enter one at a time')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
