# Generated by Django 3.2.7 on 2021-11-14 23:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='dateTimeCompleted',
        ),
        migrations.RemoveField(
            model_name='meet_member',
            name='dateTimeCompleted',
        ),
        migrations.RemoveField(
            model_name='news_letter',
            name='dateTimeCompleted',
        ),
        migrations.RemoveField(
            model_name='party_contact',
            name='dateTimeCompleted',
        ),
        migrations.RemoveField(
            model_name='policy_position',
            name='dateTimeCompleted',
        ),
        migrations.AddField(
            model_name='about',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 11, 14, 23, 1, 7, 150737, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='meet_member',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 11, 14, 23, 1, 18, 693341, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meet_member',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='news_letter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 11, 14, 23, 1, 27, 673274, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news_letter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='party_contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 11, 14, 23, 1, 29, 899796, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='party_contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='policy_position',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 11, 14, 23, 1, 32, 149855, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policy_position',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
