# Generated by Django 3.2.7 on 2021-11-01 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='card_no',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='dateTimeCompleted',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='order_no',
        ),
    ]
