# Generated by Django 3.2.7 on 2021-09-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210921_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='party_contact',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
