# Generated by Django 3.2.7 on 2021-11-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211114_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='about',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated on'),
        ),
        migrations.AlterField(
            model_name='meet_member',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='meet_member',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated on'),
        ),
        migrations.AlterField(
            model_name='news_letter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='news_letter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated on'),
        ),
        migrations.AlterField(
            model_name='party_contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='party_contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated on'),
        ),
        migrations.AlterField(
            model_name='policy_position',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='policy_position',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated on'),
        ),
    ]
