# Generated by Django 3.2.7 on 2021-11-01 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211101_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='card_no',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='card_no',
        ),
        migrations.RemoveField(
            model_name='image_video',
            name='card_no',
        ),
        migrations.RemoveField(
            model_name='meet_member',
            name='card_no',
        ),
        migrations.RemoveField(
            model_name='news_letter',
            name='card_no',
        ),
        migrations.RemoveField(
            model_name='party_contact',
            name='card_no',
        ),
        migrations.RemoveField(
            model_name='policy_position',
            name='card_no',
        ),
    ]
