# Generated by Django 3.2.7 on 2021-11-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211101_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='dateTimeCompleted',
            field=models.DateField(null=True, verbose_name='Date Completed/Updated'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='dateTimeCompleted',
            field=models.DateField(null=True, verbose_name='Date Completed/Updated'),
        ),
        migrations.AlterField(
            model_name='image_video',
            name='dateTimeCompleted',
            field=models.DateField(null=True, verbose_name='Date Completed/Updated'),
        ),
        migrations.AlterField(
            model_name='meet_member',
            name='dateTimeCompleted',
            field=models.DateField(null=True, verbose_name='Date Completed/Updated'),
        ),
        migrations.AlterField(
            model_name='news_letter',
            name='dateTimeCompleted',
            field=models.DateField(null=True, verbose_name='Date Completed/Updated'),
        ),
        migrations.AlterField(
            model_name='party_contact',
            name='dateTimeCompleted',
            field=models.DateField(null=True, verbose_name='Date Completed/Updated'),
        ),
        migrations.AlterField(
            model_name='policy_position',
            name='dateTimeCompleted',
            field=models.DateField(null=True, verbose_name='Date Completed/Updated'),
        ),
    ]
