# Generated by Django 3.2.7 on 2021-11-15 20:18

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211114_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Name Listed')),
                ('location', models.CharField(choices=[('About', 'About'), ('Archive', 'Archive'), ('Contact', 'Contact'), ('Home', 'Home'), ('Meet the Members', 'Meet the Members'), ('News Letter', 'News Letter'), ('Policy Positions', 'Policy Positions')], default='Home', max_length=20, verbose_name='Location in Website')),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.nameFile)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated on')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Name Listed')),
                ('location', models.CharField(choices=[('About', 'About'), ('Archive', 'Archive'), ('Contact', 'Contact'), ('Home', 'Home'), ('Meet the Members', 'Meet the Members'), ('News Letter', 'News Letter'), ('Policy Positions', 'Policy Positions')], default='Home', max_length=20, verbose_name='Location in Website')),
                ('video_URL', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated on')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.DeleteModel(
            name='Image_Video',
        ),
    ]
