# Generated by Django 3.2.7 on 2021-11-15 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211115_2018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Party_Contact',
        ),
    ]
