# Generated by Django 3.2.7 on 2021-11-02 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211101_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet_member',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Position Title'),
        ),
    ]
