# Generated by Django 3.2.7 on 2021-11-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_meet_member_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_letter',
            name='body',
        ),
        migrations.RemoveField(
            model_name='news_letter',
            name='bullet',
        ),
        migrations.AddField(
            model_name='news_letter',
            name='body1',
            field=models.TextField(max_length=3000, null=True, verbose_name=' Body 1 --- Enter one paragraph at a time for page break'),
        ),
        migrations.AddField(
            model_name='news_letter',
            name='body2',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name=' Body 2 (Optional) --- Enter one paragraph at a time for page break'),
        ),
        migrations.AddField(
            model_name='news_letter',
            name='body3',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name=' Body 3 (Optional) --- Enter one paragraph at a time for page break'),
        ),
        migrations.AddField(
            model_name='news_letter',
            name='body4',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name=' Body 4 (Optional) --- Enter one paragraph at a time for page break'),
        ),
        migrations.AddField(
            model_name='news_letter',
            name='body5',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name=' Body 5 (Optional) --- Enter one paragraph at a time for page break'),
        ),
        migrations.AddField(
            model_name='news_letter',
            name='bullet1',
            field=models.TextField(blank=True, max_length=260, null=True, verbose_name=' Bullet Points 1 (Optional) --- This will be after all of the paragraphs *Enter one at a time'),
        ),
        migrations.AddField(
            model_name='news_letter',
            name='bullet2',
            field=models.TextField(blank=True, max_length=260, null=True, verbose_name=' Bullet Points 2 (Optional) --- This will be after all of the paragraphs *Enter one at a time'),
        ),
        migrations.AddField(
            model_name='news_letter',
            name='bullet3',
            field=models.TextField(blank=True, max_length=260, null=True, verbose_name=' Bullet Points 3 (Optional) --- This will be after all of the paragraphs *Enter one at a time'),
        ),
        migrations.AddField(
            model_name='news_letter',
            name='bullet4',
            field=models.TextField(blank=True, max_length=260, null=True, verbose_name=' Bullet Points 4 (Optional) --- This will be after all of the paragraphs *Enter one at a time'),
        ),
        migrations.AddField(
            model_name='news_letter',
            name='bullet5',
            field=models.TextField(blank=True, max_length=260, null=True, verbose_name=' Bullet Points 5 (Optional) --- This will be after all of the paragraphs *Enter one at a time'),
        ),
    ]
