# Generated by Django 3.2.7 on 2021-11-02 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211102_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_video',
            name='dateTimeCompleted',
        ),
        migrations.RemoveField(
            model_name='image_video',
            name='order_no',
        ),
    ]
