# Generated by Django 3.2.7 on 2021-11-13 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20211104_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_video',
            name='location',
            field=models.CharField(choices=[('About', 'About'), ('Archive', 'Archive'), ('Contact', 'Contact'), ('Home', 'Home'), ('Meet the Members', 'Meet the Members'), ('News Letter', 'News Letter'), ('Policy Positions', 'Policy Positions')], default='Home', max_length=20, verbose_name='Location in Website'),
        ),
        migrations.AlterField(
            model_name='policy_position',
            name='bullet',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Position Bullet Points (Optional) --- This will be after all of the paragraphs *Enter one at a time'),
        ),
        migrations.AlterField(
            model_name='policy_position',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Position Description (Optional)'),
        ),
        migrations.AlterField(
            model_name='policy_position',
            name='position_name',
            field=models.CharField(max_length=60, null=True, verbose_name='Position Display Name'),
        ),
    ]
