# Generated by Django 3.2.7 on 2021-11-13 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20211113_0248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy_position',
            old_name='bullet',
            new_name='bullet_point',
        ),
    ]
