# Generated by Django 3.2.7 on 2021-11-13 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20211113_0325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy_position',
            old_name='bullet_point',
            new_name='bullet',
        ),
    ]
