# Generated by Django 3.2.7 on 2021-11-13 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_bullet_point_policy_position_bullet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy_position',
            name='bullet',
        ),
        migrations.AddField(
            model_name='policy_position',
            name='bullet1',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Position Bullet Points (Optional) --- This will be after the paragraph *Enter one at a time'),
        ),
        migrations.AddField(
            model_name='policy_position',
            name='bullet2',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Position Bullet Points (Optional) --- This will be after the paragraph *Enter one at a time'),
        ),
        migrations.AddField(
            model_name='policy_position',
            name='bullet3',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Position Bullet Points (Optional) --- This will be afterthe paragraph *Enter one at a time'),
        ),
        migrations.AddField(
            model_name='policy_position',
            name='bullet4',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Position Bullet Points (Optional) --- This will be afterthe paragraph *Enter one at a time'),
        ),
    ]
