# Generated by Django 3.2.7 on 2021-11-13 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20211113_0404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About'},
        ),
        migrations.AlterModelOptions(
            name='image_video',
            options={'verbose_name': 'Image or Video', 'verbose_name_plural': 'Images or Videos'},
        ),
    ]
