# Generated by Django 3.2.7 on 2021-11-13 21:53

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20211113_0430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth'), ('Fifth', 'Fifth'), ('Sixth', 'Sixth')], default='First', max_length=20, verbose_name='Location on Page')),
                ('dateTimeCompleted', models.DateField(null=True, verbose_name='Date Completed/Updated')),
                ('imageName', models.CharField(max_length=50, null=True, verbose_name='Name of Image')),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.nameFile)),
            ],
            options={
                'verbose_name': 'Carousel Image',
                'verbose_name_plural': 'Carousel Images',
            },
        ),
        migrations.AlterField(
            model_name='about',
            name='bullet',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Bullet Point'),
        ),
        migrations.AlterField(
            model_name='about',
            name='paragraph',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Paragraph/ Body'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Name Listed'),
        ),
        migrations.AlterField(
            model_name='image_video',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Name Listed'),
        ),
        migrations.AlterField(
            model_name='meet_member',
            name='about',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name="Member's Bio"),
        ),
        migrations.AlterField(
            model_name='meet_member',
            name='name',
            field=models.CharField(max_length=60, null=True, verbose_name="Member's Name"),
        ),
    ]
